name: 'Pull Request Target Branch Check'

description: "Checks the target branch of a pull request and helps to avoid merging it to a wrong one"

inputs:
  branch_file:
    description: "Name of the branch file. The content of the file is the name of the branch"
    default: ".branch"
  source_branch:
    description: "Source branch of the pull request"
    default: "origin/${{ github.head_ref }}"

runs:
  using: "composite"
  steps:
    - run: '"$GITHUB_ACTION_PATH/pull-request-target-branch-check.sh" "$SOURCE_BRANCH" "$TARGET_BRANCH" "$BRANCH_FILE"'
      shell: bash
      env:
        SOURCE_BRANCH: ${{ inputs.source_branch }}
        TARGET_BRANCH: ${{ github.base_ref }}
        BRANCH_FILE: ${{ inputs.branch_file }}
